services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/symfony:/var/www/symfony
    depends_on:
      - db
    environment:
      - SYMFONY_ENV=prod
    networks:
      - app-network
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/react-app/build:/var/www/react-app/build
      - ./backend/symfony/public:/var/www/symfony/public
    ports:
      - "8080:80"
    depends_on:
      - php
      - react
    networks:
      - app-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/react-app:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
